version: '3.8'
services:
  # Config Server (standalone)
  config1:
    image: mongo:latest
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--bind_ip_all", "--port", "27021"]
    ports:
      - "27021:27021"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "config1_data:/data/db"
    networks:
      - mongo-cluster

  # Shard 1 (single-member replica set)
  shard1:
    image: mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--bind_ip_all", "--port", "27031"]
    ports:
      - "27031:27031"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "shard1_data:/data/db"
    networks:
      - mongo-cluster

  # Shard 2 (single-member replica set)
  shard2:
    image: mongo:latest
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--bind_ip_all", "--port", "27032"]
    ports:
      - "27032:27032"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "shard2_data:/data/db"
    networks:
      - mongo-cluster

  # Mongos Router
  mongos:
    image: mongo:latest
    command: ["mongos", "--configdb", "configReplSet/config1:27021", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mongo-cluster
    depends_on:
      - config1
      - shard1
      - shard2

volumes:
  config1_data:
  shard1_data:
  shard2_data:

networks:
  mongo-cluster:
    driver: bridge
